volumes:
  nginx-shared:
  migrations:

services:
  nginx:
    image: nginx:alpine
    hostname: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-shared:/nginx
    depends_on:
      - web

  # Redis для кэширования и Celery broker
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 3

  # RabbitMQ для очередей (опционально, можно использовать только Redis)
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  # PostgreSQL для Safe Transaction Service
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 5s
      retries: 3

  # Основной веб-сервис Safe Transaction Service
  web:
    image: safeglobal/safe-transaction-service:latest
    env_file:
      - .env.sts
    depends_on:
      - db
      - redis
    working_dir: /app
    ports:
      - "8888:8888"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - nginx-shared:/nginx
      TODO: Давай попробуем использовать механизм миграций чтобы все параметры, контракты, админа применить во время деплоя, добавив просто 1 миграцию в файл
      - migrations:/app/migration
    command: docker/web/run_web.sh

  # Воркер для индексации и основной обработки
  indexer-worker: &worker
    image: safeglobal/safe-transaction-service:latest
    env_file:
      - .env.sts
    environment:
      RUN_MIGRATIONS: 1
      WORKER_QUEUES: "default,indexing,processing"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - redis
      - rabbitmq
    command: docker/web/celery/worker/run.sh

  contracts-tokens-worker:
    <<: *worker
    environment:
      WORKER_QUEUES: "contracts,tokens"

  scheduler:
    <<: *worker
    command: docker/web/celery/scheduler/run.sh

  # Мониторинг Celery (опционально)
  flower:
    <<: *worker
    command: docker/web/celery/flower/run.sh
    ports:
      - "5555:5555"
    profiles:
      - debug
