name: Build and Deploy Nest Application

on:
  push:
    branches: [main, develop]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  CWD: $CURRENT_DIR

jobs:
  build-image-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "pkg/example"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set environment variables based on branch
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "ECR_REPO_URI=009160070963.dkr.ecr.us-east-1.amazonaws.com/multisig/example-prod" >> $GITHUB_ENV
            echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
            echo "ARGO_PATH=prod/prod-a-ue1-cluster/multisignature-safe/example-deployment.yaml" >> $GITHUB_ENV
            echo "DEPLOY_ENV=prod" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "develop" ]]; then
            echo "ECR_REPO_URI=009160070963.dkr.ecr.eu-central-1.amazonaws.com/multisig/example-dev" >> $GITHUB_ENV
            echo "AWS_REGION=eu-central-1" >> $GITHUB_ENV
            echo "ARGO_PATH=dev/dev-a-eu1-cluster/multisignature-safe/example-deployment.yaml" >> $GITHUB_ENV
            echo "DEPLOY_ENV=dev" >> $GITHUB_ENV
          else
            echo "Unsupported branch: $BRANCH_NAME"
            exit 1
          fi

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build -t $ECR_REPO_URI:latest .

      - name: Tag Docker image
        run: |
          docker tag $ECR_REPO_URI:latest $ECR_REPO_URI:${{ github.sha }}

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REPO_URI:latest
          docker push $ECR_REPO_URI:${{ github.sha }}

      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          owner: 'KASPACOM'
          repositories: 'argo-cd'
          app-id: ${{ secrets.ARGO_GH_APP_ID }}
          private-key: ${{ secrets.ARGO_GH_APP_PRIVATE_KEY }}

      - name: Checkout ArgoCD repository
        uses: actions/checkout@v3
        with:
          repository: KASPACOM/argo-cd
          token: ${{ steps.generate-token.outputs.token }}

      - name: Update image tag in ArgoCD repository
        working-directory: ${{ env.CWD }}
        run: |
          sed -i "s|image: .*|image: $ECR_REPO_URI:${{ github.sha }}|" $ARGO_PATH
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add $ARGO_PATH
          git commit -m "Update $DEPLOY_ENV-multisignature-example image to ${{ github.sha }}"
          git push
